accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

intj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscriptions/', include('subscriptionapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update')
]

accountapp/models.py
from django.db import models

# Create your models here.

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='article') # 작성자
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='project')
    title = models.CharField(max_length=200, null=True) # 제목
    image = models.ImageField(upload_to='article/', null=False) # 이미지
    content = models.TextField(null=True) # 내용

    created_at = models.DateField(auto_now_add=True, null=True) # 작성일시

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True # input 비활성화 및 value 값을 바꿔서 보내도 서버에서 받지 않음

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm

# Create your views here.
from articleapp.models import Article
from profileapp.models import Profile

has_ownership = [account_ownership_required, login_required]

class AccountCreateView(CreateView):
    model = User # django에서 기본으로 제공해주는 모델
    form_class = UserCreationForm # django에서 제공해주는 회원가입 form
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/create.html'

@method_decorator(login_required, 'get')
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'
    context_object_name = 'target_user' # template에서 사용하는 user 객체 이름을 설정(다른 사람이 왔을 때도 정보를 보여줄 수 있게)
    paginate_by = 5

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align: center; max-width: 600px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Sign up</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align: center; max-width: 600px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input value="탈퇴" type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div style="text-align:center; max-width: 500px; margin: 4rem auto;">

        <!-- target_user의 profile이 있을 때 -->
        {% if target_user.profile %}
            <!-- profile image -->
            <img src="{{ target_user.profile.image.url }}" alt="profile image"
                 style="height: 12rem; width: 12rem; border-radius: 20rem;
                 margin-bottom: 2rem; object-fit: cover;">
            <!-- nickname -->
            <h2 style="font-family: 'NanumSquare';">
                {{ target_user.profile.nickname }}
            {% if target_user == user %}
                <a class="material-icons"
                   style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
                   href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                    edit
                </a>
            </h2>
            {% endif %}
            <!-- message -->
            <h5 style="margin: 3rem 0;">
                {{ target_user.profile.message }}
            </h5>
        <!-- target_user의 profile이 없을 때 -->
        {% else %}
            <!-- target_user와 현재 로그인 user가 같을 때 -->
            {% if target_user == user %}
                <div class="text-center">
                    <h5>프로필 정보가 없습니다.</h5>
                </div>
                <a href="{% url 'profileapp:create' %}"
                    class="btn btn-dark rounded-pill"
                    style="margin: 1rem 1rem;">
                    Create Profile
                </a>
            <!-- target_user와 현재 로그인 user가 같지 않을 때 -->
            {% else %}
                <div class="text-center">
                    <h5>프로필 정보가 없습니다.</h5>
                </div>
            {% endif %}
        {% endif %}

        {% if target_user == user %}
        <div class="text-center mt-3">
            <a class="material-icons"
               style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
               href="{% url 'accountapp:update' pk=target_user.pk %}">
                password
            </a>
            <a class="material-icons"
               style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;"
               href="{% url 'accountapp:delete' pk=target_user.pk %}">
                exit_to_app
            </a>
        </div>
        {% endif %}
    </div>
    <hr>
    <div>
        {% include 'snippets/article_list_fragment.html' with article_list=object_list %}
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align: center; max-width: 600px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Login</h4>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
<!--            {{ form }}-->
            {% bootstrap_form form %} <!-- bootstrap이 적용 된 form -->
            <input type="submit" class="btn btn-dark rounded-pill col-12 mt-3">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align: center; max-width: 600px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Change Password</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}